# Generated by Django 3.2.5 on 2022-10-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madlee', '0003_auto_20220816_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
