
GINKGO_SEPERATOR = '|'

KEY_DAEMON      = 'GINKGO-DAEMON'
KEY_SCRIPTS     = 'GINKGO-SCRIPTS'
KEY_YEAR_TS     = 'GINKGO-YEAR-TS'
KEY_LEAVES      = 'GINKGO-LEAVES'
KEY_LAST_SLOT   = 'GINKGO-LAST-SLOT'

CMD_NEW_LEAF = 'NEW-LEAF'
CMD_ENSURE   = 'ENSURE'

MSG_NEW_SLOT = 'NEW-SLOT'
MSG_ENSURED  = 'ENSURED'



SHA_PUSH        = 'PUSH'
SHA_NEW_LEAF    = CMD_NEW_LEAF
SHA_MISSING     = 'MISS'
SHA_LOAD        = 'LOAD'
SHA_JOIN        = 'JOIN'
SHA_JOIN_SUB    = 'JOIN-SUB'
SHA_AUTO_LEAF   = 'AUTO-LEAF'
SHA_GET_SLOT    = 'GET-SLOT'
SHA_GET_LAST    = 'GET-LAST'
SHA_ALL_SLOTS   = 'ALL-SLOTS'
SHA_NEWER_SLOTS = 'NEWER-SLOTS'

