from ..const import *

GINKGO_SEPERATOR = '|'

KEY_DAEMON      = 'GINKGO-DAEMON'
KEY_SCRIPTS     = 'GINKGO-SCRIPTS'
KEY_YEAR_TS     = 'GINKGO-YEAR-TS'
KEY_LEAVES      = 'GINKGO-LEAVES'


CMD_NEW_LEAF = 'NEW-LEAF'

MSG_NEW_SLOT = 'NEW-SLOT'


SHA_PUSH        = 'PUSH'
SHA_NEW_LEAF    = CMD_NEW_LEAF